# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Triple2Layer
                                 A QGIS plugin
 this plugin imports data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-22
        copyright            : (C) 2023 by Nerval Junior 
        email                : nerval1@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Triple2Layer class from file Triple2Layer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Triple2Layer import Triple2Layer
    return Triple2Layer(iface)
