# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Triple2Layer
                                 A QGIS plugin
 this plugin imports data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Nerval Junior 
        email                : nerval1@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QProgressDialog
from qgis.PyQt.QtWidgets import QAction, QComboBox, QCheckBox, QLineEdit, QTableWidgetItem, QFileDialog, QInputDialog
from qgis.core import QgsVectorLayer, QgsField, QgsGeometry, QgsFeature, QgsProject,  Qgis, QgsTask, QgsTaskManager, QgsApplication, QgsMessageLog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Triple2Layer_dialog import Triple2LayerDialog
import os.path
import json
import os

from functools import partial

plugin_dir = os.path.dirname(__file__)

from SPARQLWrapper import SPARQLWrapper, JSON, N3
from SPARQLWrapper.SPARQLExceptions import SPARQLWrapperException

import datadotworld as dw
from requests.exceptions import HTTPError, Timeout, ConnectionError

import re


dic_attr_type = {
    "String": QVariant.String,
    "Int": QVariant.Int,
    "Double": QVariant.Double,
}


path_plugin = os.path.dirname(__file__)
path_file = os.path.join(path_plugin, "endpoint.json")


class Triple2Layer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Triple2Layer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&QGISSPARQL')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Triple2Layer', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Triple2Layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Triple2Layer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&QGISSPARQL'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = Triple2LayerDialog()
            self.file_name = None
            self.endpoint_defaut()
            self.dlg.pushButton.clicked.connect(self.execute)
            self.dlg.button_box.rejected.connect(self.close)
            self.dlg.buttonSPARQL.clicked.connect(self.open_sparql)
            self.dlg.actionToken.triggered.connect(self.set_token)
            self.dlg.comboSourceType.textActivated.connect(
                self.endpoint_defaut)

        # show the dialog
        self.dlg.show()


    def execute(self):
        if self.check_attributes():
            self.save_endpoint()
            self.import_layer()
        else:
            self.erroOnLoadLayer = True
            self.errorMessage = "Select the geo atribute"
            self.check_if_imported_layer()
            print ("erroor")

    def set_token(self):

        token, ok = QInputDialog.getText(
            self.dlg, "Data.World Token", "Enter with token")
        if (ok and token != ""):
            os.environ['DW_AUTH_TOKEN'] = token

    def check_attributes(self):
        selected_geo = False

        self.geo_column = ""
        self.saveAttrs = []
        self.id_column = "id:integer"
        for row in range(self.dlg.tableAttributes.rowCount()):
            line_edit = self.dlg.tableAttributes.cellWidget(row, 4)
            attr_name = line_edit.text()

            item = self.dlg.tableAttributes.item(row, 3)
            var_name = item.text()

            check_id = self.dlg.tableAttributes.cellWidget(row, 1)
            check_geo = self.dlg.tableAttributes.cellWidget(row, 2)
            check = self.dlg.tableAttributes.cellWidget(row, 0)
            combo_type = self.dlg.tableAttributes.cellWidget(row, 5)

            if check_id.isChecked():
                self.id_column = attr_name

            if check_geo.isChecked():
                self.geo_column = attr_name
                selected_geo = True

            if check.isChecked() or check_id.isChecked():
                self.saveAttrs.append(
                    (attr_name, dic_attr_type[combo_type.currentText()], var_name))
        print ("check", selected_geo)
        return selected_geo

    def load_data_world(self, time):
        """Load data from a Data.world dataset using SPARQL."""
        QgsMessageLog.logMessage('Loading data from Data.world...', 'Triple2Layer')

        try:
            ds = dw.query(self.dlg.lineEndpoint.text(),
                      self.sparql, query_type='sparql')

            QgsMessageLog.logMessage('Data successfully loaded from Data.world.', 'Triple2Layer')
            dict = ds.dataframe.to_dict('records')
            return dict
        except HTTPError as e:
            msg = f'HTTP error while connecting to Data.world: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except Timeout:
            msg = 'Connection to Data.world timed out. Check your internet connection.'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except ConnectionError as e:
            msg = f'Could not connect to Data.world: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except Exception as e:
            msg = f'Unexpected error loading from Data.world: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = 'Fail to load data from Data.world: check dataset name and token'
            self.erroOnLoadLayer = True


    def load_triple_store(self, time):
        """Load data from a SPARQL triple store endpoint."""
        try:
            sparql = SPARQLWrapper(self.dlg.lineEndpoint.text())
            sparql.setQuery(self.sparql)
            sparql.setReturnFormat(JSON)
            results = sparql.query().convert()
            return results["results"]["bindings"]
        except SPARQLWrapperException as e:
            msg = f'SPARQL query error: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except HTTPError as e:
            msg = f'HTTP error while connecting to triple store: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except Timeout:
            msg = 'Connection to triple store timed out. Check the endpoint URL.'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = msg
            self.erroOnLoadLayer = True
        except Exception as e:
            msg = f'Unexpected error loading from triple store: {e}'
            QgsMessageLog.logMessage(msg, 'Triple2Layer', level=Qgis.Critical)
            self.errorMessage = 'Fail to load data from triple store: check endpoint URL'
            self.erroOnLoadLayer = True

    def get_value(self, row: dict, attr: str, source: str = 'dw'):
        """Extract attribute value from a query result row.

        Args:
            row: A single result row (dict) from the SPARQL query.
            attr: The attribute/variable name to extract.
            source: Data source type — 'triple' for triple stores, 'dw' for Data.world.

        Returns:
            The attribute value as a string, or None if not found.
        """
        try:
            if source == 'triple':
                return row[attr]['value']
            else:
                return row[attr]
        except KeyError:
            QgsMessageLog.logMessage(
                f"Attribute '{attr}' not found in result row. Available keys: {list(row.keys())}",
                'Triple2Layer', level=Qgis.Warning)
            return None

    def create_layer(self, source, time, records):

        layer = QgsVectorLayer('Polygon?crs=epsg:4326?field=' +
                               self.id_column, self.dlg.lineLayer.text(), "memory")
        pr = layer.dataProvider()
        layer.startEditing()
        # não funcionou com o map ???
        attributes = [QgsField(x[0], x[1]) for x in self.saveAttrs]
        pr.addAttributes(attributes)
        layer.updateFields()

        features = []
        i = 0
        total = 0
        total = len(records)
        #verifica se o atributo de geometria esta correto
        geom = QgsGeometry.fromWkt( self.get_value(records[0], self.geo_column, source))
        print ("geommmmmm", geom)
        if geom.isNull():
            self.erroOnLoadLayer = True
            self.errorMessage = "Invalid geometry attribute, select a wkt attribute value"
            self.check_if_imported_layer()
            return

        QgsMessageLog.logMessage(
            'A tarefa já está concluindo. '+str(time) + "-" + str(total), 'Triple2Layer')

        progressDialog = QProgressDialog(
            "Importing layer...", "Cancel", 0, 0, self.iface.mainWindow())
        progressDialog.setWindowTitle("Importing layer")
        progressDialog.setLabelText("Importing features...")
        progressDialog.setMaximum(total)
        progressDialog.setValue(0)
        progressDialog.show()
        progressDialog.setCancelButton(None)

        for row in records:
            fet = QgsFeature()
            geom = QgsGeometry.fromWkt(
                self.get_value(row, self.geo_column, source))
            fet.setGeometry(geom)
            attrs = []
            for attr in self.saveAttrs:
                attrs.append(self.get_value(row, attr[2], source))
            fet.setAttributes(attrs)
            features.append(fet)
            i += 1
            progressDialog.setValue(i)
            progressDialog.setLabelText(
                "Importing feature {} of {}".format(i, total))
            QCoreApplication.processEvents()

        layer.addFeatures(features)
        layer.updateExtents()
        layer.commitChanges()
        QgsProject.instance().addMapLayer(layer)

        progressDialog.close()

        self.iface.messageBar().pushMessage(
            "Success", "Imported layer",
            level=Qgis.Success, duration=3)
        

    def check_if_imported_layer (self):
        self.iface.messageBar().clearWidgets()
        if self.erroOnLoadLayer == True:
            self.iface.messageBar().pushMessage(
            "Fail", self.errorMessage,
            level=Qgis.Warning, duration=3)
            


    def import_from_dataworld(self):

        if "DW_AUTH_TOKEN" not in os.environ:
            self.iface.messageBar().pushMessage(
                "Ooops", "Token not defined",
                level=Qgis.Info, duration=3
            )
            self.set_token()
        else:
            QgsMessageLog.logMessage('criando tarefa.', 'Triple2Layer')
            self.task = QgsTask.fromFunction('Importing a layer', self.load_data_world, on_finished=partial(self.create_layer, 'dw'))
            self.task.taskCompleted.connect(self.check_if_imported_layer)
            QgsApplication.taskManager().addTask(self.task)

    def save_endpoint(self):
        caminho = self.buscapath()
        source = self.dlg.comboSourceType.currentText()
        try:
            with open(caminho, "r") as arquivo:
                endpoints = json.load(arquivo)
        except (FileNotFoundError, json.JSONDecodeError):
            endpoints = {}

        url_ds = self.dlg.lineEndpoint.text()
        endpoints[source] = url_ds

        try:
            with open(caminho, "w") as arquivo:
                json.dump(endpoints, arquivo)
        except IOError as e:
            QgsMessageLog.logMessage(
                f'Could not save endpoint configuration: {e}', 'Triple2Layer', level=Qgis.Warning)

    def endpoint_defaut(self):
        caminho = self.buscapath()
        source = self.dlg.comboSourceType.currentText()
        try:
            with open(caminho, "r") as arquivo:
                endpoints = json.load(arquivo)
            endpoint = endpoints[source]
            self.dlg.lineEndpoint.setText(endpoint)
        except (FileNotFoundError, json.JSONDecodeError, KeyError):
            self.dlg.lineEndpoint.setText("")

    def buscapath(self):
        path_plugin = os.path.dirname(__file__)
        path_file = os.path.join(path_plugin, "endpoint.json")
        return path_file

    def import_from_triple(self):
        QgsMessageLog.logMessage('criando tarefa.', 'Triple2Layer')
        self.task = QgsTask.fromFunction(
            'Importing a layer', self.load_triple_store, on_finished=partial(self.create_layer, 'triple'))
        self.task.taskCompleted.connect(self.check_if_imported_layer)
        QgsApplication.taskManager().addTask(self.task)

    def import_layer(self):

        self.erroOnLoadLayer = False

        source = self.dlg.comboSourceType.currentText()

        self.dlg.close()

        self.iface.messageBar().pushMessage(
                "Importing a layer", "Importing a layer ...",
                level=Qgis.Info, duration=10)

        if source == "Triple Store Endpoint":
            self.import_from_triple()
        else:
            self.import_from_dataworld()

    def open_sparql(self):
        self.file_name = str(QFileDialog.getOpenFileName(
            caption="Defining input file", filter="SPARQL(*.sparql)")[0])
        self.dlg.lineSPARQL.setText(self.file_name)

        try:
            with open(self.file_name, 'r') as file:
                data = file.read()
                self.sparql = data
                self.fill_table(data)
        except FileNotFoundError:
            QgsMessageLog.logMessage(
                f'SPARQL file not found: {self.file_name}', 'Triple2Layer', level=Qgis.Warning)
        except IOError as e:
            QgsMessageLog.logMessage(
                f'Could not read SPARQL file: {e}', 'Triple2Layer', level=Qgis.Warning)

    def geo_selected (self,row, state):
        #self.dlg.tableAttributes.
        w1 = self.dlg.tableAttributes.cellWidget(row, 4)
        w2 = self.dlg.tableAttributes.cellWidget(row, 5)
        if state == QtCore.Qt.Checked:
            w1.setEnabled(False)
            w2.setEnabled(False)  
            self.dlg.pushButton.setEnabled(True)
        else:
            w1.setEnabled(True)
            w2.setEnabled(True)
            self.dlg.pushButton.setEnabled(False)
        print (state)
        

    def fill_table(self, s):
        """Parse SPARQL query variables and populate the attribute configuration table.

        Uses a regex to extract variables from the SELECT clause, which handles
        tabs, multiple spaces, DISTINCT/REDUCED keywords, and subqueries reliably.
        """
        match = re.search(r'SELECT\s+(DISTINCT\s+|REDUCED\s+)?(.*?)\s+WHERE', s, re.IGNORECASE | re.DOTALL)
        if not match:
            QgsMessageLog.logMessage(
                'Could not parse SPARQL query: SELECT...WHERE clause not found.',
                'Triple2Layer', level=Qgis.Warning)
            self.iface.messageBar().pushMessage(
                "Warning", "Could not parse the SPARQL file. Check the SELECT...WHERE syntax.",
                level=Qgis.Warning, duration=5)
            return

        variables_str = match.group(2)

        # Handle SELECT * wildcard
        if variables_str.strip() == '*':
            QgsMessageLog.logMessage(
                'SELECT * is not supported. Please list variables explicitly.',
                'Triple2Layer', level=Qgis.Warning)
            self.iface.messageBar().pushMessage(
                "Warning", "SELECT * is not supported. Please list variables explicitly.",
                level=Qgis.Warning, duration=5)
            return

        attributes = re.findall(r'\?(\w+)', variables_str)

        if not attributes:
            QgsMessageLog.logMessage(
                'No variables found in SELECT clause.', 'Triple2Layer', level=Qgis.Warning)
            return

        self.dlg.tableAttributes.setRowCount(len(attributes))
        self.dlg.tableAttributes.setColumnCount(6)
        self.dlg.tableAttributes.setHorizontalHeaderLabels(
            ["Import?", "IDColumn?", "GeoColumn?", "Variable", "Attribute name", "Attribute type"])

        for i, attr in enumerate(attributes):
            self.dlg.tableAttributes.setCellWidget(i, 0, QCheckBox())
            self.dlg.tableAttributes.setCellWidget(i, 1, QCheckBox())
            geo_check = QCheckBox()
            geo_check.stateChanged.connect(partial(self.geo_selected, i))
            self.dlg.tableAttributes.setCellWidget(i, 2, geo_check)
            self.dlg.tableAttributes.setItem(i, 3, QTableWidgetItem(attr))
            self.dlg.tableAttributes.setCellWidget(i, 4, QLineEdit(attr))
            comboBox = QComboBox()
            comboBox.addItem("String")
            comboBox.addItem("Int")
            comboBox.addItem("Double")
            self.dlg.tableAttributes.setCellWidget(i, 5, comboBox)

    def close(self):
        self.dlg.setVisible(False)