# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sergio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisparql-triple2layer/export_observation_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportObservationDialogBase(object):
    def setupUi(self, ExportObservationDialogBase):
        ExportObservationDialogBase.setObjectName("ExportObservationDialogBase")
        ExportObservationDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(ExportObservationDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(ExportObservationDialogBase)
        self.button_box.accepted.connect(ExportObservationDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ExportObservationDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportObservationDialogBase)

    def retranslateUi(self, ExportObservationDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ExportObservationDialogBase.setWindowTitle(_translate("ExportObservationDialogBase", "Export Observation"))
